# Generated by Django 4.0.5 on 2023-02-01 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 6, 39, 49, 181675, tzinfo=utc), null=True),
        ),
    ]
