# Generated by Django 4.0.5 on 2023-02-01 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_alter_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 12, 13, 33, 611683, tzinfo=utc), null=True),
        ),
    ]
