# Generated by Django 4.0.5 on 2023-02-02 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 9, 57, 16, 261180, tzinfo=utc), null=True),
        ),
    ]
