# Generated by Django 4.0.5 on 2023-02-02 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 10, 13, 39, 158539, tzinfo=utc), null=True),
        ),
    ]
