# Generated by Django 4.0.3 on 2022-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='templates/profiles'),
        ),
    ]
