# Generated by Django 4.0.3 on 2022-04-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа')], default='rent', max_length=15),
        ),
    ]
