# Generated by Django 4.0.3 on 2022-04-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pub_date']},
        ),
    ]
