# Generated by Django 4.0.3 on 2022-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_theme', models.CharField(max_length=40, verbose_name='theme')),
                ('message_text', models.CharField(max_length=1000, verbose_name='text')),
                ('phone', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
