# Generated by Django 4.0.5 on 2023-02-01 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_alter_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 7, 46, 0, 119790, tzinfo=utc), null=True),
        ),
    ]
