# Generated by Django 4.0.3 on 2022-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
