# Generated by Django 4.0.5 on 2023-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('pay', models.IntegerField()),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='garages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rooms',
        ),
        migrations.AddField(
            model_name='product',
            name='isVIP',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
