# Generated by Django 4.0.5 on 2023-02-01 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0009_remove_product_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='favorite_prods', to=settings.AUTH_USER_MODEL),
        ),
    ]
